# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction -to- Ecology
description:      'A course covering population, community, and ecosystem ecology for undergraduates'
url:              http://atredennick.github.io/ecology_class/
baseurl:          /ecology_class
email:            atredenn@gmail.com

author:
  name:           'Andrew Tredennick'
  url:            https://twitter.com/atredennick

github:
  repo:           https://github.com/atredennick/ecology_class
  #               Be sure the 'Issues' feature is activated in 'Settings'
